name: 'XML 2020'
description: 'XSLT-based linting for XML and XSD Files'
inputs:
  xml-file:
    description: 'The source (.xml) file'
    required: true
  xml-schema-file:
    description: 'The schema (.xsd) file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.xml-file }}
    - ${{ inputs.xml-schema-file }}
